### ISSUE TITLE
[SCRIPT] To-do

### ISSUE THREAD

**Issue by Daksh777** [Daksh777/SpotifyNoPremium#35]
- [x] Add check for Microsoft Store Spotify
- [x] Use archive instead of git
- [ ] Default `prefs_path` to C:\Users\USERNAME\AppData\Roaming\Spotify\prefs in Spicetify config
- [x] Pin message box to top
